name: Pull Request automation

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  pr-automation:
    name: Pull Request automation
    runs-on: ubuntu-latest
    if: github.actor == 'renovate[bot]'

    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}